title: Traktor Documentation
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Navigation structure
nav_sort: case_sensitive
search_enabled: true
permalink: pretty

just_the_docs:
  collections:
    pages:
      output: true