title: Traktor Documentation
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: true
permalink: pretty

just_the_docs:
  collections: {}
  navigation:
    structure: custom
